require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/routes.rb
    - db/schema.rb
    - db/migrate/**/*
    - db/seeds/*.rb
    - db/seeds.rb
    - vendor/**/*
    - Gemfile
    - Gemfile.package
    - Guardfile
    - Rakefile
    - config.ru
    - vendors/**/*

Layout/LineLength:
  Max: 140
  Exclude:
    - config/initializers/ioc.rb
    - db/migrate/*.rb
    - spec/**/*_spec.rb
    - spec/factories/**/*.rb
    - plugins/*/config/initializers/ioc.rb
    - plugins/*/lib/**/*.rb
    - plugins/**/spec/**/*.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - config/**/*.rb
    - spec/**/*.rb
    - plugins/*/spec/**/*.rb

Style/ExponentialNotation:
  Enabled: false

Style/ExplicitBlockArgument:
  Exclude:
    - app/use_cases/concerns/transactionable.rb

Metrics/ClassLength:
  Exclude:
    - app/controllers/**/*.rb
    - plugins/*/lib/**/**/railtie.rb

Metrics/AbcSize:
  Max: 22

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/initializers/ioc.rb
    - spec/**/*_spec.rb
    - spec/factories/**/*.rb
    - plugins/*/config/initializers/ioc.rb
    - plugins/*/spec/**/*
    - plugins/*/lib/**/**/railtie.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Lint/MissingSuper:
  Exclude:
    - app/carriers/**/*.rb
    - app/contracts/**/*.rb
    - plugins/**/lib/**/**/handlers/*.rb
    - plugins/**/lib/**/**/contracts/*.rb

Rails/DynamicFindBy:
  Enabled: false

Rails/ShortI18n:
  Enabled: false

Rails/WhereNot:
  Enabled: false

Style/NumberedParameters:
  Enabled: false

Style/NumberedParametersLimit:
  Max: 2

Metrics/MethodLength:
  Max: 12
  Exclude:
    - plugins/**/lib/**/**/presenters/*.rb

Lint/ConstantDefinitionInBlock:
  Exclude:
    - plugins/**/spec/**/*.rb
    - plugins/**/spec/*.rb

Rails/SkipsModelValidations:
  Exclude:
    - plugins/codd-*/lib/codd/**/**/*.rb

Style/EmptyCaseCondition:
  Enabled: false

Rails/WhereEquals:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/integration/**/*.rb

RSpec/MultipleExpectations:
  Max: 8

RSpec/ExampleLength:
  Exclude:
    - plugins/**/spec/**/*.rb
  Max: 8

RSpec/ScatteredSetup:
  Exclude:
    - spec/integration/**/*.rb
    - plugins/*/spec/integration/**/*.rb

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/integration/**/*.rb
    - plugins/*/spec/integration/**/*.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - plugins/*/spec/**/*.rb

RSpec/LetSetup:
  Exclude:
    - plugins/*/spec/**/*.rb

RSpec/NamedSubject:
  Exclude:
    - plugins/**/spec/**/*.rb
    - plugins/**/spec/*.rb

RSpec/LeakyConstantDeclaration:
  Exclude:
    - plugins/**/spec/*.rb

RSpec/VerifiedDoubles:
  Exclude:
    - plugins/**/spec/**/*.rb

RSpec/ContextWording:
  Exclude:
    - plugins/**/spec/**/*.rb

RSpec/ContextMethod:
  Exclude:
    - plugins/**/spec/**/*.rb

RSpec/SharedContext:
  Exclude:
    - plugins/**/spec/**/**/*.rb

RSpec/SubjectDeclaration:
  Exclude:
    - plugins/**/spec/**/*.rb

RSpec/NestedGroups:
  Max: 4

RSpec/AnyInstance:
  Exclude:
    - plugins/**/spec/**/*.rb

FactoryBot/AssociationStyle:
  Enabled: false
FactoryBot/IdSequence:
  Enabled: false

