version: "3.8"

services:
  db:
    image: postgres:16
    container_name: mmd
    volumes:
      - mmd_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:4.0.12-alpine
    ports:
      - 6379:6379

volumes:
  mmd_db:
networks:
  mmd_data_network:
