version: '3.8'

services:
  db:
    image: postgres:16
    container_name: mmd
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - mmd_data_volume:/var/lib/postgresql/data
volumes:
  mmd_data_volume:
networks:
  mmd_data_network: