defaults: &defaults
  adapter: <%= Settings.database.adapter %>
  encoding: <%= Settings.database.encoding %>
  host: <%= Settings.database.host %>
  port: <%= Settings.database.port %>
  user: <%= Settings.database.username %>
  password: <%= Settings.database.password %>
  database: <%= Settings.database.database %>
  pool: <%= Settings.database.pool || 5 %>
  checkout_timeout: <%= Settings.database.checkout_timeout || 5 %>

development:
  <<: *defaults
test:
  <<: *defaults
  database: core_test

production:
  <<: *defaults
