defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: dokku-postgres-mmd-db
  port: 5432
  user: postgres
  password: 5236a545df0f2ff74b944ed7019c27d9
  database: mmd_db
  pool: <%= Settings.database.pool || 5 %>
  checkout_timeout: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *defaults
test:
  <<: *defaults
  database: test_db

production:
  <<: *defaults
