defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  port: 5432
  user: <%= Settings.database.username %>
  password: <%= Settings.database.password %>
  database: <%= Settings.database.database %>
  pool: 5

development:
  <<: *defaults

test:
  <<: *defaults
  database: mmd_test

staging:
  <<: *defaults
  host: mmd_db

production:
  <<: *defaults
