database:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 0.0.0.0
  port: 5432
  database: "lifelongdata"
  #  database: rails_touch_test
  username: "yourpersonalmanager"
  password: "UxyDFSUa8qVNWh9"
